import json
import re

def get_missing_long_strings():
    return {
        "Effects how far gnomes will travel for better food and drink": "Влияет на то, как далеко гномы пойдут за лучшей едой и питьем",
        "Remove floor and mine section below into stairs": "Убрать пол и прорубить лестницу вниз",
        "Gnomoria is a sandbox management game and is ": "Gnomoria — это песочница и симулятор управления, ",
        "played by indirectly controlling your gnomes ": "где вы косвенно руководите своими гномами, ",
        "by creating jobs for them, designating areas ": "создавая для них задачи, размечая зоны мира ",
        "of the world as specific places and adjusting ": "как особые места и настраивая различные ",
        "settings. You can pause and unpause the game ": "параметры. Вы можете ставить игру на паузу ",
        "at anytime to manage your kingdom and watch ": "в любое время, чтобы управлять королевством и ",
        "Each gnome needs to eat, drink and sleep and ": "Каждому гному нужно есть, пить и спать, и ",
        "it's your job to help provide for them. As you ": "ваша задача — обеспечить их этим. По мере того как вы ",
        "build your kingdom, your overall worth will ": "строите королевство, его общая ценность будет ",
        "increase, attracting more gnomes to join you as ": "расти, привлекая новых гномов, а также ",
        "well as enemies who threaten your gnomes. ": "врагов, которые угрожают вашим гномам.",
        "Your only objective is to help your gnomes ": "Ваша единственная цель — помочь гномам ",
        "survive in this harsh world for as long as ": "выжить в этом суровом мире так долго, ",
        "Gnomoria takes place in a randomly generated ": "Действие Gnomoria происходит в случайно созданном ",
        "3D world with many resources to discover and ": "3D-мире со множеством ресурсов для поиска и ",
        "The world is split into a 3D grid of cells and is ": "Мир разбит на 3D-сетку клеток и полностью ",
        "fully deformable. Each cell can be harvested ": "изменяем. Каждую клетку можно раскопать ",
        "for its resource and used to be rebuilt ": "ради ресурсов и использовать для постройки ",
        "elsewhere or crafted into new items. ": "в другом месте или создания новых вещей.",
        "Gnomes in a Squad behave based on that ": "Гномы в Отряде ведут себя на основе ",
        "Squad's Formation. Every Squad can be set to ": "Построения Отряда. Каждый Отряд может ",
        "use the same Formation or a new Formation can ": "использовать одно Построение, либо можно ",
        "Formations are made up of 5 Positions which ": "Построения состоят из 5 Позиций, которые ",
        "are defined in the Positions window. These ": "определяются в окне Позиций. Эти ",
        "Positions can be the same or different. ": "Позиции могут быть одинаковыми или разными.",
        "Positions tell individual Squad Members how to ": "Позиции указывают отдельным Членам Отряда, как ",
        "behave while the Formation tells the Squad what ": "вести себя, тогда как Построение говорит Отряду, что ",
        "There are 3 basic Formation options which ": "Есть 3 базовые настройки Построения, которые ",
        "Perform attack orders - With this option set, ": "Выполнять приказы об атаке — при этой опции ",
        "gnomes will seek out and fight enemies that you ": "гномы будут искать и атаковать врагов, которых вы ",
        "Defend gnomes - Formations with this option ": "Защищать гномов — Построения с этой опцией ",
        "will automatically track down and fight enemies ": "автоматически выслеживают и сражаются с врагами, ",
        "that are engaged in combat with other gnomes. ": "вступившими в бой с другими гномами.",
        "Avoid enemies - This option changes the Squads ": "Избегать врагов — эта опция меняет поведение Отрядов ",
        "default behavior of attacking enemies on ": "с атаки врагов при встрече на избегание ",
        "sight, to avoiding any enemy in sight. ": "любых видимых врагов.",
        "Positions have a Uniform, which tells the Squad ": "У Позиций есть Униформа, которая говорит Члену ",
        "Member what they are allowed to equip when ": "Отряда, что ему разрешено экипировать, когда ",
        "they are in this Position. There are also a few ": "он находится в этой Позиции. Также есть несколько ",
        "Pursue lost targets - If line of sight to the ": "Преследовать пропавшие цели — если прямая видимость ",
        "current target is lost, Squad Members will move ": "к цели потеряна, Члены Отряда будут двигаться ",
        "Maintain distance - Squad Members will attempt ": "Держать дистанцию — Члены Отряда попытаются ",
        "to stay at maximum weapon range from their ": "оставаться на максимальной дальности оружия от ",
        "Retreat if bleeding - Squad Members will ": "Отступать при кровотечении — Члены Отряда будут ",
        "disengage from combat to heal bleeding ": "выходить из боя, чтобы вылечить кровоточащие ",
        "Assist Squad Leader - With this option set, ": "Помогать Командиру — при этой опции, ",
        "Squad Members will always target the same ": "Члены Отряда будут всегда атаковать ту же ",
        "enemy as their Squad Leader instead of ": "цель, что и Командир Отряда, вместо того чтобы ",
        "Additionally, each Position can set a Perk ": "Кроме того, для каждой Позиции можно задать Особенность, ",
        "which will give a unique bonus when certain ": "которая даст уникальный бонус при выполнении ",
        "A Uniform defines what a gnome is allowed to ": "Униформа определяет, что гному разрешено ",
        "equip. Uniforms can be set to only equip ": "надевать. Униформу можно настроить на экипировку только ",
        "specific items, materials or only items of a ": "конкретных предметов, материалов или только предметов ",
        "Additionally, each Formation can set a Perk ": "Кроме того, для каждого Построения можно задать Особенность, ",
        "which will give every Squad Member a unique ": "которая даст каждому Члену Отряда уникальный ",
        "bonus when certain conditions are met. ": "бонус при выполнении определенных условий.",
        "When starting out, gnomes don't know anything ": "В самом начале гномы ничего не знают ",
        "about Mechanisms, however, gnomes love to ": "о Механизмах, однако гномы любят возиться ",
        "Once a Tinker Bench has been constructed, ": "Как только будет построен Верстак Жестянщика, ",
        "gnomes with the Tinkering skill will get to work ": "гномы с навыком Жестянщика приступят к работе, ",
        "attaching gears to random objects, hammering ": "прикрепляя шестеренки к случайным объектам, стуча ",
        "things and eventually somehow, unlocking new ": "по вещам и, в конечном итоге, каким-то образом открывая новые ",
        "Links are Mechanisms whose sole purpose is to ": "Связи — это Механизмы, единственная цель которых — ",
        "Axles are straight line connections that can go ": "Оси — это прямые соединения, которые могут идти ",
        "horizontally or vertically. Horizontal axles ": "горизонтально или вертикально. Горизонтальные оси ",
        "can be built directly into the floor without ": "можно встроить прямо в пол без ",
        "Gearboxes allow axles to connect from ": "Коробки передач позволяют соединять оси с ",
        "different directions as well as intersect. ": "разных направлений, а также пересекать их. ",
        "Gearboxes are large and require the floor to ": "Коробки передач большие и требуют, чтобы пол ",
        "be removed before it can be set in place. ": "был удален перед их установкой.",
        "Toggle switches are a special kind of link that ": "Переключатели — это особый вид связи, который ",
        "can connect or disconnect Mechanisms around ": "может подключать или отключать Механизмы вокруг ",
        "it. The Lever can be manually flipped on or off ": "себя. Рычаг можно вручную включать или выключать, ",
        "and requires a gnome with the Mechanic skill to ": "и для его использования нужен гном с навыком Механика ",
        "operate. Pressure Plates flip on or off when ": "нажимать. Нажимные Плиты включаются или выключаются, когда ",
        "stepped on and can be set by a Mechanic to be ": "на них наступают, и могут быть настроены Механиком на включение ",
        "Power Sources unsurprisingly provide power ": "Источники энергии, как ни удивительно, дают энергию ",
        "and are required for a mechanical system to ": "и необходимы для работы механической системы ",
        "operate. Some Power Sources are operated ": "в целом. Некоторые источники управляются ",
        "manually, while others are automatic or even ": "вручную, тогда как другие работают автоматически или даже ",
        "Devices have different functions when ": "Устройства имеют разные функции, когда они ",
        "powered or unpowered, such as moving a ": "включены или выключены, например, передвижение ",
        "mechanical wall or opening and closing a hatch. ": "механической стены или открытие/закрытие люка.",
        "Traps are a special kind of Mechanism that ": "Ловушки — это особый вид Механизмов, который ",
        "don't connect to other Mechanisms. Traps are ": "не соединяется с другими Механизмами. Ловушки ",
        "self contained and all of their parts are ": "полностью автономны, и все их детали находятся ",
        "When a trap is set, it already has the ": "Когда ловушка установлена, в ней уже есть ",
        "necessary power and parts to be triggered by ": "нужная энергия и детали для срабатывания на ",
        "an enemy. The catch, is that once it is ": "врага. Загвоздка в том, что после срабатывания ",
        "triggered it requires a gnome with the Mechanic ": "потребуется гном с навыком Механика, чтобы ",
        "skill to reset it before it can be used again. ": "сбросить её, прежде чем её можно будет использовать снова.",
        "Workshops are where your gnomes will go to ": "Мастерские — это места, куда ваши гномы отправятся ",
        "craft new items. Each Workshop has its own set ": "создавать новые предметы. Каждая мастерская имеет свой набор ",
        "of recipes for crafting. Each recipe requires ": "рецептов для крафта. Каждый рецепт требует ",
        "a skill to be used for crafting and only gnomes ": "определенного навыка для создания, и только гномам ",
        "with that skill enabled will be allowed to craft ": "с включенным навыком будет позволено создавать ",
        "When a gnome accepts the craft job, they will ": "Когда гном принимает задачу по крафту, он ",
        "gather the required items and bring them to the ": "соберет необходимые предметы и принесет их в ",
        "Workshop to craft. Crafting jobs can be set to ": "Мастерскую. Задачи по крафту можно установить на ",
        "\"Repeat\" which will repeatedly craft the item ": "«Повторять», что будет постоянно создавать этот предмет, ",
        "as long as the requirements are met. Craft jobs ": "пока выполняются требования. Задачи также ",
        "can also be set to \"Craft To\" a specified ": "можно установить в режим «Скрафтить до» указанного ",
        "number, and gnomes will automatically craft ": "количества, и гномы автоматически создадут ",
        "that item when the current quantity in stock is ": "этот предмет, если его количество на складе ",
        "When creating Craft jobs at a workshop, ": "При создании задач крафта в мастерской, ",
        "specific materials can be selected per ": "можно выбрать конкретные материалы для каждого ",
        "ingredient. The first ingredient in the recipe ": "ингредиента. Первый ингредиент в рецепте ",
        "usually determines the material type of the ": "обычно определяет тип материала ",
        "newly crafted item. In some cases, such as ": "созданного предмета. В некоторых случаях, таких как ",
        "crafting metal alloys or turning logs into coal, ": "создание сплавов металлов или превращение бревен в уголь, ",
        "the newly crafted item will have a new material. ": "созданный предмет будет иметь новый материал.",
        "An item's material is what determines its ": "Материал предмета определяет его ",
        "properties. For many items, this is primarily ": "свойства. Для многих предметов это в первую очередь ",
        "the color. Some items like tables and chairs, ": "цвет. Некоторые предметы, такие как столы и стулья, ",
        "can be crafted from wood or stone and are ": "могут быть созданы из дерева или камня и ",
        "visually different. The material also plays a ": "визуально различаются. Материал также играет ",
        "part in determining the value of an item as well ": "роль в определении ценности предмета, а также ",
        "as combat related properties. For example, a ": "свойств, связанных с боем. Например, ",
        "gold statue will be more valuable than a silver ": "золотая статуя будет ценнее серебряной ",
        "statue and bronze armor is stronger than ": "статуи, а бронзовая броня прочнее ",
        "Terrain constructions add to the world and ": "Ландшафтные постройки добавляются в мир и ",
        "typically change how everything moves through ": "обычно меняют то, как всё перемещается по ",
        "the world. This includes building walls, floors, ": "миру. Это включает в себя строительство стен, полов, ",
        "Walls block movement and floors provide ": "Стены блокируют движение, а полы предоставляют ",
        "something to stand on. Ramps and stairs both ": "поверхность, на которой можно стоять. Скаты и лестницы ",
        "enable vertical travel in the world. A ramp ": "позволяют перемещаться по миру по вертикали. Для ската ",
        "requires a wall for support or it will collapse. ": "требуется стена в качестве опоры, иначе он обрушится. ",
        "Gnomes travel across ramps diagonally and ": "Гномы перемещаются по скатам по диагонали, и для этого ",
        "require an adjacent floor at the top of the ": "требуется прилегающий пол на вершине ",
        "Stairs can be built free standing and require ": "Лестницы можно строить свободно стоящими, они не требуют ",
        "no additional support. Gnomes travel across ": "дополнительной опоры. Гномы перемещаются по ",
        "stairs by directly moving up or down before ": "лестницам, двигаясь прямо вверх или вниз перед тем как ",
        "continuing, thus making stairs slightly slower ": "продолжить путь, из-за чего лестницы немного медленнее, ",
        "than ramps. However, since a gnome can stand ": "чем скаты. Однако, так как гном может стоять ",
        "on top of stairs, it allows them to reach ": "на вершине лестницы, это позволяет им достигать ",
        "otherwise innaccesible areas and build new ": "иначе недоступных зон и строить новые ",
        "Furniture are constructions that are typically ": "Мебель — это постройки, которые обычно ",
        "used for decoration but can also serve a ": "используются для украшения, но могут также служить некой ",
        "purpose. They can be used to boost the value ": "цели. Их можно использовать для повышения ценности ",
        "of a room, or used directly such as beds, ": "комнаты, или использовать напрямую, как кровати, ",
        "Most furniture are first crafted in a workshop ": "Большая часть мебели сначала создается в мастерской, ",
        "and then placed in the world through the Build ": "а затем размещается в мире через меню Строить ",
        "Storage constructions are special types of ": "Постройки для хранения — это особый тип ",
        "Furniture that can be used to store items. They ": "Мебели, которую можно использовать для хранения предметов. Их ",
        "can only be placed in a Stockpile and are ": "можно размещать только на Складах, и они ",
        "automatically used when stocking items into ": "используются автоматически при размещении предметов на ",
        "Workshops are required to craft new items. ": "Мастерские необходимы для создания новых вещей. ",
        "Each Workshop has a set of recipes for ": "У каждой Мастерской есть свой набор рецептов для ",
        "crafting new items and are at the heart of ": "крафта новых предметов, и они лежат в основе ",
        "The Stockpile designation is used to instruct ": "Зона Склад нужна для того, чтобы указать ",
        "your gnomes where to place items. A Stockpiles ": "гномам, куда нести вещи. Главная настройка складов — ",
        "main setting is selecting which items are ": "выбор того, какие предметы разрешено помещать ",
        "allowed to be placed in its area. Stockpiles are ": "на их территорию. Склады — это ",
        "an important designation for managing a ": "важнейшая разметка для управления ",
        "Gnomes with the Hauling skill enabled, will move ": "Гномы с активным навыком Переноски будут нести ",
        "allowed items to this Stockpile, provided there ": "разрешенные вещи на этот Склад, пока там ",
        "is room. Stockpiles have a Priority setting and ": "есть место. У складов есть Приоритет, и склады с ",
        "higher priority (lower number) Stockpiles will ": "высшим приоритетом (меньшим числом) будут ",
        "be stocked before a lower priority (higher ": "заполняться раньше складов с низким приоритетом ",
        "number). Stockpiles can also be renamed and ": "(большим числом). Склады также можно переименовать и ",
        "temporarily Suspended so that gnomes ignore ": "временно Приостановить, чтобы гномы игнорировали ",
        "Normally, 1 item can be placed in each square ": "Обычно 1 предмет занимает 1 клетку, пока склад ",
        "until the Stockpile is full. Storage items, such ": "не заполнится. Предметы хранения, такие как ",
        "as crates, barrels and bags, can be built on ": "ящики, бочки и мешки, можно ставить на склады, ",
        "Stockpiles so that each square can hold ": "чтобы увеличить вместимость клеток ",
        "The Farm designation is used to instruct your ": "Зона Ферма нужна для того, чтобы указать вашим ",
        "gnomes where to plant crops, such as wheat, ": "гномам, где сажать культуры, такие как пшеница, ",
        "strawberries and cotton. Farms must be ": "земляника и хлопок. Фермы нужно размещать ",
        "designated over dirt. Each Farm is assigned a ": "на земле. Каждой Ферме назначается ",
        "specific Crop and gnomes with the Farming skill ": "конкретная Культура, и гномы с навыком Земледелия ",
        "enabled will work the Farm automatically. ": "будут работать на ней автоматически.",
        "Your Farmers will begin by harvesting any ": "Ваши фермеры начнут со сбора урожая, ",
        "crops that are ready. If there are no crops to ": "если он готов. Если собирать нечего, ",
        "harvest they will plant seeds on tilled soil. If ": "они посадят семена на вспаханной почве. Если ",
        "there is no other work to be done on the Farm, ": "на Ферме больше нет другой работы, ",
        "your gnomes will till any remaining untilled soil. ": "ваши гномы вспашут оставшуюся невспаханную почву.",
        "Farms have a Priority setting and higher ": "У Ферм есть настройка Приоритета, и Фермы с ",
        "priority (lower number) Farms will be worked ": "высшим приоритетом (меньшим числом) будут ",
        "before a lower priority (higher number). Farms ": "обрабатываться раньше Ферм с низким приоритетом. Фермы ",
        "can also be renamed and temporarily Suspended ": "также можно переименовать и временно Приостановить, ",
        "The Pasture designation is used to instruct ": "Зона Пастбище нужна для того, чтобы указать ",
        "your gnomes where to keep livestock, such as ": "гномам, где держать скот, такой как ",
        "yaks, alpacas and emus. Pastures must be ": "яки, альпаки и эму. Пастбища нужно размещать ",
        "designated over grass. Each Pasture is ": "на траве. Каждому Пастбищу назначается ",
        "assigned a specific animal and gnomes with the ": "конкретное животное, и гномы с навыком ",
        "Animal Husbandry skill enabled will work the ": "Животноводства будут работать на ",
        "Pasture automatically. Each animal takes up ": "Пастбище автоматически. Каждое животное занимает ",
        "space in the pasture and different types of ": "место на пастбище, и разным животным требуется ",
        "animals have different space requirements. ": "разное количество свободного места.",
        "Your Ranchers will begin by herding unpastured ": "Ваши Животноводы начнут с того, что загонят бродячих ",
        "animals into the Pasture. If there are no ": "животных на Пастбище. Если бродячих ",
        "roaming livestock they will tend to the animals ": "животных нет, они займутся уходом за ними: ",
        "by sheering wool or milking them. Animals that ": "будут стричь шерсть или доить их. Животные, ",
        "share a Pasture will breed on their own. ": "находящиеся на одном Пастбище, размножаются сами.",
        "Pastures have a Priority setting and higher ": "У Пастбищ есть настройка Приоритета, и Пастбища с ",
        "priority (lower number) Pastures will be worked ": "высшим приоритетом (меньшим числом) будут ",
        "before a lower priority (higher number). ": "обрабатываться раньше Пастбищ с низким приоритетом. ",
        "Pastures can also be renamed, temporarily ": "Пастбища также можно переименовывать, временно ",
        "Suspended so that gnomes ignore it and set a ": "Приостанавливать, чтобы гномы игнорировали их, и задавать ",
        "limit of males and females allowed. ": "лимит на количество самцов и самок.",
        "The Grove designation is used to instruct your ": "Зона Роща нужна для того, чтобы указать вашим ",
        "gnomes where to plant trees. Groves must be ": "гномам, где сажать деревья. Рощи нужно размещать ",
        "designated over dirt. Each Grove is assigned a ": "на земле. Каждой Роще назначается ",
        "specific tree and gnomes will work the Grove ": "определенное дерево, и гномы будут работать в Роще ",
        "Gnomes with the Horticulture skill enabled will ": "Гномы с активным навыком Садоводства ",
        "start by planting tree clippings. Once a tree ": "начнут с посадки побегов. Как только дерево ",
        "has grown, gnomes with the Horticulture skill ": "вырастет, гномы с навыком Садоводства ",
        "will cut clippings to be used for growing more ": "будут срезать новые побеги для посадки других ",
        "trees. Some trees, such as apples trees, can be ": "деревьев. С некоторых деревьев (например, с яблонь) можно ",
        "harvested and Gnomes with the Farming skill will ": "собирать урожай, и гномы с навыком Земледелия будут ",
        "pick fruit on the trees. Finally, gnomes with ": "срывать с них фрукты. И наконец, гномы с навыком ",
        "Woodcutting will fell trees in your Grove. ": "Лесозаготовки будут рубить деревья в вашей Роще.",
        "Each Grove job can be turned on or off to allow ": "Каждую задачу в Роще можно включить или выключить для ",
        "for specialization, such as a grove of apple ": "создания специализации, например, рощи яблонь, ",
        "trees that only allows fruit to be picked. ": "в которой разрешено только собирать фрукты.",
        "Groves have a Priority setting and higher ": "У Рощ есть настройка Приоритета, и Рощи с ",
        "priority (lower number) Groves will be worked ": "высшим приоритетом будут ",
        "Groves can also be renamed and temporarily ": "Рощи также можно переименовывать и временно ",
        "Suspended so that gnomes ignore it. ": "Приостанавливать, чтобы гномы игнорировали их.",
        "Personal Quarters are where your gnomes will ": "Личные Покои — это место, где гномы в первую очередь ",
        "first look when they need sleep. A Personal ": "будут искать ночлег. Для использования Личных ",
        "Quarters will require a bed to be constructed ": "Покоев потребуется построить кровать ",
        "If a gnome does not already have a Personal ": "Если у гнома еще нет Личных ",
        "Quarter, they will automatically claim a vacant ": "Покоев, он автоматически займет свободную ",
        "one as their own. You can also manually assign ": "комнату как свою собственную. Вы также можете назначать ",
        "or reassign Personal Quarters as you see fit. ": "или переназначать Личные Покои по своему усмотрению.",
        "Personal Quarters are unique in that the Worth ": "Личные Покои уникальны тем, что Ценность ",
        "of the room directly effects how well rested ": "комнаты напрямую влияет на качество отдыха ",
        "the gnome becomes. Each construction in the ": "гнома. Каждая постройка в ",
        "room adds its value to the rooms total value. ": "комнате добавляет свою ценность к общей ценности комнаты. ",
        "The higher the room value, the better sleep the ": "Чем выше ценность комнаты, тем лучше будет сон в ней, ",
        "room provides and the longer a gnome can go ": "и тем дольше гном сможет работать ",
        "A Dormitory is another room where gnomes will ": "Казарма — это еще одна комната, куда гномы ",
        "go when they need sleep. Unlike the Personal ": "идут спать. В отличие от Личных ",
        "Quarters, a Dormitory cannot be assigned to a ": "Покоев, Казарма не может быть назначена ",
        "specific gnome and will be shared by all ": "определенному гному, её будут использовать все ",
        "Provided that there is an available bed, gnomes ": "При условии наличия свободной кровати, гномы ",
        "without a Personal Quarters will sleep in a ": "без Личных Покоев будут спать в ",
        "Dormitory. Unlike the Personal Quarters, the ": "Казарме. В отличие от Личных Покоев, общая ",
        "total Worth of the Dormitory has no effect on ": "Ценность Казармы никак не влияет на то, ",
        "how well the gnome sleeps. However, sleeping in ": "насколько хорошо гном выспится. Тем не менее, сон на ",
        "a bed is still prefered over sleeping on the ": "кровати по-прежнему предпочтительнее сна на ",
        "Dining Rooms are used to designate where your ": "Зона Столовая используется для указания места, где вашим ",
        "gnomes are allowed to eat. Gnomes will look for ": "гномам разрешено есть. Гномы будут искать ",
        "an open chair that is next to a table and bring ": "свободный стул рядом со столом и приносить ",
        "their food there to eat. If there are no ": "свою еду туда, чтобы поесть. Если ",
        "available chairs, gnomes will stand and eat but ": "свободных стульев нет, гномы будут есть стоя, но ",
        "One Dining Room can be selected to be the Great ": "Одну Столовую можно выбрать в качестве Большого ",
        "Hall. Gnomes without work will idle in the Great ": "Зала. Гномы без работы будут бездельничать в Большом ",
        "Hall and wait for something to do. Each ": "Зале в ожидании задач. Каждая ",
        "construction in the Great Hall adds to its total ": "постройка в Большом Зале добавляет ценности к его общей ",
        "Worth. The Worth of your Great Hall directly ": "Ценности. Ценность вашего Большого Зала напрямую ",
        "contributes to attracing wandering gnomads to ": "влияет на привлечение странствующих гномадов в ",
        "The Hospital is where gnomes will go for healing ": "Госпиталь — это место, куда гномы отправятся для лечения ",
        "or to get help eating and drinking. At one time, ": "или чтобы получить помощь с едой и питьем. Одновременно ",
        "a Hospital can provide for as many gnomes as ": "Госпиталь может обслуживать столько гномов, сколько ",
        "there are beds in it. Like other designations, ": "в нем есть кроватей. Как и другие зоны, ",
        "Hospitals can have a Priority set as well as be ": "Госпитали могут иметь настройку Приоритета, а также их можно ",
        "Normally, gnomes will be able to heal themselves ": "Обычно гномы могут вылечить себя сами ",
        "with bandages on their own. If a gnome has lost ": "с помощью бинтов. Если гном потерял ",
        "the use of both hands, or has a serious wound, ": "возможность использовать обе руки, или получил серьезную рану, ",
        "they will go to a hospital bed and wait for a ": "он отправится на больничную койку и будет ждать ",
        "Doctor. Gnomes with the Medic skill enabled will ": "Доктора. Гномы с активным навыком Медицины будут ",
        "bring bandages to the injured gnome and heal ": "приносить бинты раненому гному и лечить ",
        "If a gnome has lost the use of both hands, they ": "Если гном потерял возможность использовать обе руки, он ",
        "can no longer feed themselves. These gnomes ": "больше не может сам есть. Такие гномы ",
        "will go to a hospital bed when they are hungry ": "отправятся на больничную койку, когда проголодаются ",
        "or thirsty. Gnomes with the Caretaking skill ": "или захотят пить. Гномы с активным навыком Смотрителя ",
        "enabled will bring food or drink to these ": "будут приносить еду или питье таким ",
        "Guard Stations are designations that specify ": "Охранные Посты — это зоны, которые указывают, ",
        "where a Military Squad should defend. Gnomes ": "где Военный Отряд должен держать оборону. Гномы ",
        "in the assigned Squad will roam through out the ": "из назначенного Отряда будут бродить по всей ",
        "Guard Stations can be renamed to more easily ": "Охранные Посты можно переименовать, чтобы легче ",
        "Unlike other Designations, Patrol Routes are ": "В отличие от других Зон, Маршруты Патрулирования ",
        "made up of a series of waypoints instead of 1 ": "состоят из серии точек пути вместо 1 ",
        "large area. Like other Military Designations, a ": "большой зоны. Как и другие Военные Зоны, ",
        "Squad is assigned to a Patrol Route and Patrol ": "Отряд прикрепляется к Маршруту Патрулирования, и ",
        "Gnomes in the assigned Squad will follow the ": "Гномы из назначенного Отряда будут следовать по ",
        "Patrol Route from point to point. Upon reaching ": "Маршруту Патрулирования от точки к точке. Достигнув ",
        "the end of the Patrol Route, they will turn ": "конца Маршрута Патрулирования, они развернутся ",
        "around and follow the route in reverse. If the ": "и пойдут по маршруту в обратном направлении. Если ",
        "Loop option is selected, gnomes will instead ": "выбрана опция «Зациклить», гномы вместо этого ",
        "move from the last point back to the first and ": "пойдут от последней точки сразу к первой и ",
        "Your gnomes will need food and drink to surive ": "Вашим гномам потребуется еда и питье для выживания ",
        "and rest to keep working hard. Gnomes will feed ": "и отдых, чтобы продолжать усердно работать. Гномы будут кормиться ",
        "themselves, provided that there are food and ": "сами, при условии, что в запасах есть еда и ",
        "drink in supply. Crafting more advanced food ": "питье. Создание более сложной еды ",
        "and drink provides increased nourishment for ": "и питья обеспечивает лучшее питание для ",
        "your gnomes -- meaning they can go longer ": "ваших гномов — это значит, что они могут дольше обходиться ",
        "without food or drink. Sometimes your gnomes ": "без еды и питья. Иногда ваши гномы ",
        "will also craft higher quality food and drinks, ": "также будут создавать еду и напитки более высокого качества, ",
        "which will also provide more nourishment than ": "что также обеспечит больше сытости, чем ",
        "Eventually your gnomes will get tired and need ": "В конце концов ваши гномы устанут и им потребуется ",
        "to rest. Gnomes prefer to sleep in comfort over ": "отдохнуть. Гномы предпочитают спать в комфорте, а не ",
        "resting on the cold hard floor. However, if ": "отдыхать на холодном твердом полу. Однако, если ",
        "there aren't any beds available, they will rest ": "нет доступных кроватей, они будут отдыхать ",
        "their eyes for a few minutes anywhere they ": "с закрытыми глазами пару минут где угодно, где ",
        "Gnomes take pride in their living space and ": "Гномы гордятся своим жилым пространством и ",
        "prefer to have their own personal quarters in ": "предпочитают иметь собственные личные покои в ",
        "your kingdom. The more valuable the personal ": "вашем королевстве. Чем ценнее личные ",
        "quarters is, the more at ease the gnome ": "покои, тем комфортнее себя чувствует гном, ",
        "becomes resulting in better sleep. The quality ": "что приводит к лучшему сну. Качество ",
        "of sleep a gnome gets will let them work for ": "сна гнома позволит ему работать ",
        "longer before needing to sleep again. Sleeping ": "дольше, прежде чем ему снова понадобится спать. Сон ",
        "in a bed is better than the floor and sleeping in ": "в кровати лучше, чем на полу, а сон в ",
        "a nice personal room will provide better sleep ": "хорошей личной комнате обеспечит лучший сон ",
        "Gnomes have different skill levels in many ": "Гномы имеют разные уровни навыков во многих ",
        "areas as well as general attributes which ": "сферах, а также общие характеристики, которые ",
        "effect all skills. Each job has 1 skill ": "влияют на все навыки. Каждая задача имеет 1 навык, ",
        "associated with it as well as 1 or more ": "связанный с ней, а также 1 или несколько ",
        "attributes. When a gnome completes a job, they ": "характеристик. Когда гном завершает задачу, он ",
        "become more experienced in that skill and train ": "становится более опытным в этом навыке и тренирует ",
        "their attributes. Higher skill levels allow ": "свои характеристики. Более высокие уровни навыков позволяют ",
        "Each gnome is assigned a profession. ": "Каждому гному назначается профессия. ",
        "Professions can be shared among different ": "Профессии могут быть общими для разных ",
        "gnomes or customized for each gnome. A ": "гномов или настроены индивидуально для каждого. ",
        "profession is just a collection of which skills ": "Профессия — это просто набор тех навыков, которые ",
        "gnomes are allowed to use. If a job requires a ": "разрешено использовать гному. Если для задачи требуется ",
        "skill that a gnome isn't allowed to use, then ": "навык, который гному не разрешено использовать, то ",
        "You can pan your view around the world with the ": "Вы можете перемещать камеру по миру с помощью ",
        "keyboard (default WASD) as well as with the ": "клавиатуры (по умолчанию WASD), а также с помощью ",
        "mouse by left or right clicking and dragging. ": "мыши, удерживая левую или правую кнопку и перетаскивая. ",
        "You can also rotate between 4 viewing angles ": "Вы также можете вращать камеру между 4 углами обзора ",
        "with the keyboard (default , and .). ": "с помощью клавиатуры (по умолчанию , и .). ",
        "Gnomoria is a world with not just width and ": "Gnomoria — это мир не только с шириной и ",
        "height but also depth. The current depth is ": "высотой, но и с глубиной. Текущая глубина ",
        "displayed in the upper left corner of the ": "отображается в левом верхнем углу ",
        "screen. You can move the current depth up or ": "экрана. Вы можете изменять текущую глубину вверх или ",
        "down with the scroll wheel on your mouse or the ": "вниз с помощью колесика мыши или ",
        "Left clicking on the ground will display a list ": "Клик левой кнопкой мыши по земле покажет список ",
        "of everything at that position. Clicking on ": "всего, что находится на этой позиции. Клик по ",
        "anything in that list will provide more ": "любому элементу в этом списке предоставит больше ",
        "Right clicking on some objects will bring up a ": "Клик правой кнопкой мыши по некоторым объектам вызовет ",
        "menu for interacting with it. For example, right ": "меню для взаимодействия с ними. Например, правый ",
        "clicking on a Farm will show the Farm options ": "клик по Ферме покажет настройки Фермы ",
        "and details about that Farm. Otherwise, right ": "и детали этой Фермы. В остальных случаях, правый ",
        "clicking will bring up an action menu for ": "клик вызовет меню действий для ",
        "creating jobs and interacting with the world. ": "создания задач и взаимодействия с миром. ",
        "The Kingdom menu shows overall information ": "Меню Королевства показывает общую информацию ",
        "Here you will find the name of your kingdom, ": "Здесь вы найдете название вашего королевства, ",
        "game difficulty and total Kingdom Worth. The ": "сложность игры и общую Ценность Королевства. ",
        "World Seed is also displayed here and can be ": "Зерно Мира также отображается здесь и может быть ",
        "reused when creating a new world to generate ": "использовано повторно при создании нового мира для генерации ",
        "There is also overall information about your ": "Также здесь есть общая информация о ваших ",
        "workshops, farms, pastures and rooms. ": "мастерских, фермах, пастбищах и комнатах. ",
        "This is where you can see information about ": "Здесь вы можете посмотреть информацию о ",
        "The first thing you'll see is a general overview ": "Первое, что вы увидите — это общая сводка ",
        "of some necessities like total counts of food, ": "о некоторых необходимых вещах, таких как общее количество еды, ",
        "drink, weapons and armor. The Stockpiles tab ": "питья, оружия и брони. Вкладка Склады ",
        "will list all stockpiles you've created and allow ": "перечислит все созданные вами склады и позволит ",
        "you to filter the list with the options on the ": "отфильтровать список с помощью опций ",
        "Selecting items or categories on the left of the ": "Выбор предметов или категорий в левой части ",
        "Items tab will display quantities of each item on ": "вкладки Предметы покажет количество каждого предмета ",
        "the right as well as a break down of each item ": "справа, а также детализацию по каждому предмету ",
        "The Population menu provides detailed ": "Меню Населения предоставляет подробную ",
        "information about your gnomes and their ": "информацию о ваших гномах и их ",
        "The Overview tab displays your total ": "Вкладка Сводки отображает ваше общее ",
        "population as well as number of gnomes who are ": "население, а также количество гномов, которые ",
        "currently idle. The right side of this window ": "в данный момент бездельничают. Правая часть этого окна ",
        "shows how many gnomes have been selected for ": "показывает, сколько гномов выбрано для ",
        "The Status tab lists all gnomes and their ": "Вкладка Статус перечисляет всех гномов и их ",
        "current status. Clicking on the name of a gnome ": "текущий статус. Клик по имени гнома ",
        "will bring up detailed information about that ": "выведет подробную информацию об этом ",
        "gnome. Likewise, clicking on a job will bring up ": "гноме. Аналогично, клик по задаче выведет ",
        "The Assign tab is where you can assign each ": "Вкладка Назначение — это место, где вы можете назначить каждого ",
        "The Professions tab is where you can alter and ": "Вкладка Профессии — это место, где вы можете изменять и ",
        "create new Professions. Each gnome is ": "создавать новые Профессии. Каждому гному ",
        "assigned a profession which outlines what jobs ": "назначается профессия, которая определяет, какие задачи ",
        "they are allowed to perform. Each job has a ": "ему разрешено выполнять. У каждой задачи есть ",
        "skill that is associated with it. For example, ": "навык, который с ней связан. Например, ",
        "only gnomes with a profession that has Mining ": "только гномам с профессией, в которой выбрано Шахтерство, ",
        "selected will be allowed to carry out any Mining ": "будет разрешено выполнять любые задачи Шахтерства ",
        "The Military window shows information about ": "Окно Армии показывает информацию о ",
        "your Squads and their current assignments. ": "ваших Отрядах и их текущих назначениях. ",
        "More detailed information about Squads is ": "Более подробная информация об Отрядах ",
        "The Events window provides of log of various ": "Окно Событий предоставляет журнал различных ",
        "events that can be viewed by date. There is ": "событий, которые можно просматривать по датам. Также имеется ",
        "also a detailed breakdown of each battle in the ": "подробный разбор каждой битвы во ",
        "Stock items on this floor next if possible": "Размещать предметы на этом этаже, если возможно",
        "A pine crate. Used to store various items. ": "Сосновый ящик. Используется для хранения различных предметов. "
    }

def run():
    raw_path = 'D:/steam/steamapps/common/Gnomoria/Gnomoria_en_ru.json'
    with open(raw_path, 'r', encoding='utf-8', errors='ignore') as f:
        current_data = json.load(f)

    # Применяем новые переводы из огромного списка длинных строк (без ломания регистра/границ)
    db_long = get_missing_long_strings()

    # Заменяем
    updates = 0
    for eng, rus in db_long.items():
        if eng in current_data:
            current_data[eng] = rus
            updates += 1
            
    with open(raw_path, 'w', encoding='utf-8') as f:
        json.dump(current_data, f, ensure_ascii=False, indent=2)

    print(f"Applied exactly {updates} massive paragraph translations. Total in dictionary: {len(current_data)}")

if __name__ == "__main__":
    run()
